name: Build Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Get RPi toolchain
        run: |
          wget https://github.com/sfjohnson/rpi-toolchain/releases/download/v0.0.6/arm-rpi-linux-gnueabihf.tar.xz
          tar xf arm-rpi-linux-gnueabihf.tar.xz -C ~

      - name: Make
        run: |
          make -f android30.mk
          make -f android30.mk clean
          make -f rpi.mk
          make -f rpi.mk clean
          make -f linux-x64.mk
        working-directory: ./src

      - name: Prepare output
        run: |
          zip -j include.zip include/tinyalsa/*.h
          mv src/libtinyalsa-android30.a .
          mv src/libtinyalsa-rpi.a .
          mv src/libtinyalsa-linux-x64.a .

      - name: Upload build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            include.zip
            libtinyalsa-android30.a
            libtinyalsa-rpi.a
            libtinyalsa-linux-x64.a
            LICENSE

  create-release:
    runs-on: ubuntu-22.04
    needs: [build]
    permissions:
      contents: write
    steps:
      - name: Get build output
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            include.zip
            libtinyalsa-android30.a
            libtinyalsa-rpi.a
            libtinyalsa-linux-x64.a
            LICENSE
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
